import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

type SeedText = {
  category: string;
  difficulty: string;
  content: string;
  language?: string;
};

const textData: SeedText[] = [
  { category: "general", difficulty: "easy", content: "The sun was setting behind the tall mountains, casting a warm orange glow across the quiet valley below. A gentle breeze whispered through the leaves of the ancient oak trees, making them dance in the fading light. It was a perfect evening for a long walk in the countryside, away from the noise and stress of the busy city life." },
  { category: "general", difficulty: "easy", content: "Learning to cook can be a very rewarding experience for anyone who enjoys good food and creative hobbies. Starting with simple recipes like pasta or salads helps build confidence in the kitchen before moving on to more complex dishes. Sharing a home-cooked meal with friends and family is one of the best ways to spend a weekend afternoon." },
  { category: "general", difficulty: "easy", content: "Many people find that keeping a daily journal helps them organize their thoughts and reduce stress after a long day at work. Writing down your goals and reflections allows you to track your progress over time and see how much you have grown. It only takes a few minutes each morning to set a positive tone for the rest of your day." },
  { category: "general", difficulty: "easy", content: "Traveling to new places opens your mind to different cultures and ways of living that you might never have imagined before. Whether you are exploring a small village in the mountains or a bustling metropolis, every journey offers unique lessons and memories. Meeting new people and trying local food are often the highlights of any great vacation trip." },
  { category: "general", difficulty: "easy", content: "Gardening is a peaceful hobby that allows you to connect with nature while beautifying your own backyard or balcony space. Planting seeds and watching them grow into vibrant flowers or fresh vegetables provides a deep sense of accomplishment and joy. It is also a great way to get some fresh air and light exercise during the spring and summer." },
  { category: "general", difficulty: "easy", content: "A cup of warm tea in the morning is a small pleasure that many people look forward to every single day. The gentle heat and soft aroma help you wake up slowly and feel calm before the busy hours begin. Taking a quiet moment for yourself is a simple habit that can make a big difference in how you feel." },
  { category: "general", difficulty: "easy", content: "Dogs are loyal animals that bring a lot of joy and comfort to the families who care for them. They love to play in the park, chase after balls, and greet you happily when you come home from work. Taking your dog for a walk every day is good for both your health and your happiness." },
  { category: "general", difficulty: "easy", content: "Reading a good book on a rainy afternoon is one of the best ways to relax and escape into another world. You can travel to distant places, meet interesting characters, and learn new things without leaving your comfortable chair. A cozy blanket and a hot drink make the experience even better." },
  { category: "general", difficulty: "easy", content: "Riding a bicycle is a fun and healthy way to explore your neighborhood and enjoy the fresh air outside. You can feel the wind on your face as you pedal down quiet streets and past green parks. It is also a clean and simple way to travel short distances without using a car." },
  { category: "general", difficulty: "easy", content: "Cooking breakfast on a slow weekend morning can turn an ordinary day into something special and warm. The smell of fresh bread and fruit fills the kitchen while soft music plays in the background. Sharing that first meal with the people you love is a gentle way to start the day." },

  { category: "general", difficulty: "medium", content: "The global shift towards renewable energy sources is gaining significant momentum as nations strive to meet their climate targets. Solar and wind power are becoming increasingly cost-effective, outperforming traditional fossil fuels in many international markets. However, the transition requires substantial investment in infrastructure and energy storage solutions to ensure a stable and reliable power grid for future generations." },
  { category: "general", difficulty: "medium", content: "Emotional intelligence is increasingly recognized as a vital component of effective leadership in the modern corporate environment. Leaders who possess high self-awareness and empathy are better equipped to navigate complex interpersonal dynamics and foster a culture of collaboration. By prioritizing the well-being and professional growth of their teams, they can drive long-term success and innovation within their organizations." },
  { category: "general", difficulty: "medium", content: "The rapid evolution of urban architecture reflects the changing needs and values of diverse societies throughout human history. From the grand cathedrals of the middle ages to the sleek skyscrapers of today, buildings serve as both functional spaces and cultural symbols. Sustainable design practices are now at the forefront of the industry, aiming to minimize environmental impact while maximizing efficiency." },
  { category: "general", difficulty: "medium", content: "Modern psychology explores the intricate relationship between our thoughts, emotions, and behaviors in various social contexts. Cognitive behavioral therapy has emerged as a highly effective tool for managing anxiety and depression by challenging negative thought patterns. Understanding the underlying mechanisms of the human mind can lead to improved mental health and more fulfilling relationships with others." },
  { category: "general", difficulty: "medium", content: "The history of cinema is a fascinating journey from silent black-and-white films to the immersive digital experiences of the present day. Filmmakers have always pushed the boundaries of technology to tell compelling stories that resonate with audiences on a global scale. Today, streaming platforms are revolutionizing how we consume content, making a vast library of films accessible to anyone with an internet connection." },
  { category: "general", difficulty: "medium", content: "The exploration of outer space represents one of humanity's most ambitious and collaborative scientific endeavors. Space agencies and private companies are now competing to establish a sustainable human presence on the Moon and eventually Mars. These missions require groundbreaking advances in propulsion, life support, and robotics that often benefit everyday life on Earth as well." },
  { category: "general", difficulty: "medium", content: "Nutrition science continues to evolve as researchers uncover the complex ways in which diet influences long-term health outcomes. A balanced approach that emphasizes whole foods, fiber, and moderation tends to outperform restrictive fad diets over time. Understanding how the body processes different nutrients empowers individuals to make informed and sustainable choices." },
  { category: "general", difficulty: "medium", content: "The preservation of biodiversity has become a pressing concern as human activity continues to reshape natural habitats worldwide. Ecosystems depend on a delicate balance of species, each playing a specific role in maintaining overall stability and resilience. Conservation efforts increasingly rely on both scientific research and the traditional knowledge of local communities." },
  { category: "general", difficulty: "medium", content: "Remote work has fundamentally altered the relationship between employees and the traditional office environment. While it offers greater flexibility and autonomy, it also introduces new challenges related to communication, collaboration, and work-life balance. Companies are now rethinking their policies to attract talent while maintaining a strong and cohesive organizational culture." },

  { category: "general", difficulty: "hard", content: "The epistemological foundations of contemporary scientific inquiry necessitate a rigorous adherence to the principles of empirical falsification. Theoretical frameworks must be subjected to exhaustive scrutiny and peer review to ensure their validity within the broader academic community. This relentless pursuit of objective truth remains the cornerstone of human intellectual progress, transcending ideological boundaries and cultural prejudices." },
  { category: "general", difficulty: "hard", content: "Technological singularity posits a hypothetical future point where artificial intelligence surpasses human cognitive capabilities, leading to rapid and unpredictable societal changes. Ethicists and scientists are engaged in profound debates regarding the potential risks and benefits of such an occurrence for the future of our species. Establishing robust safety protocols and alignment strategies is paramount to mitigating existential threats posed by autonomous systems." },
  { category: "general", difficulty: "hard", content: "The intricate socio-economic ramifications of globalization have led to both unprecedented prosperity and systemic inequality across various geopolitical regions. While international trade has facilitated the exchange of goods and ideas, it has also exacerbated the divide between developed and developing nations. Addressing these disparities requires a multifaceted approach involving policy reform, sustainable development, and equitable resource distribution." },
  { category: "general", difficulty: "hard", content: "Quantum entanglement describes a phenomenon where particles become interconnected in such a way that the state of one instantaneously influences the other, regardless of distance. This direct challenge to classical notions of locality and causality has profound implications for the field of quantum computing and secure communication. Experimental verification continues to push the limits of our understanding of the fundamental fabric of the universe." },
  { category: "general", difficulty: "hard", content: "The historiography of the industrial revolution reveals a complex tapestry of technological innovation, social upheaval, and environmental transformation. Examining the transition from agrarian economies to mechanized manufacturing processes provides crucial insights into the origins of modern capitalism and labor movements. This historical perspective is essential for understanding the current challenges posed by the fourth industrial revolution." },
  { category: "general", difficulty: "hard", content: "Neuroplasticity, the brain's remarkable capacity to reorganize its synaptic connections in response to experience, has revolutionized our understanding of cognition and rehabilitation. This adaptive phenomenon underpins learning, memory consolidation, and recovery from neurological injury throughout the human lifespan. Consequently, therapeutic interventions increasingly leverage targeted stimulation to harness the brain's intrinsic reparative mechanisms." },
  { category: "general", difficulty: "hard", content: "The philosophical discourse surrounding free will and determinism continues to perplex scholars across metaphysics, neuroscience, and jurisprudence. If human behavior is entirely governed by antecedent causes, the very notion of moral responsibility becomes profoundly contentious. Reconciling our subjective experience of agency with the deterministic frameworks of physical science remains an enduring intellectual challenge." },
  { category: "general", difficulty: "hard", content: "Macroeconomic policy is perpetually constrained by the intricate interplay between inflationary pressures, unemployment, and aggregate demand. Central banks must calibrate monetary instruments with meticulous precision, balancing short-term stabilization against long-term structural equilibrium. The unintended consequences of such interventions frequently reverberate across interconnected global financial systems in unpredictable ways." },
  { category: "general", difficulty: "hard", content: "The ontological status of consciousness remains one of the most intractable problems in contemporary philosophy of mind. Reductive materialists contend that subjective experience emerges wholly from neurophysiological processes, whereas dualists posit an irreducible phenomenal dimension. This so-called hard problem interrogates whether objective description can ever fully capture the qualitative texture of lived experience." },

  { category: "code", difficulty: "easy", content: "function greet(name) { return `Hello, ${name}!`; } console.log(greet('Developer'));" },
  { category: "code", difficulty: "easy", content: "const colors = ['red', 'green', 'blue']; colors.forEach(color => console.log(color));" },
  { category: "code", difficulty: "easy", content: "let count = 0; while (count < 5) { console.log(count); count++; }" },
  { category: "code", difficulty: "easy", content: "const add = (a, b) => a + b; const result = add(10, 20); export default add;" },
  { category: "code", difficulty: "easy", content: "if (isLoggedIn) { showDashboard(); } else { redirectToLogin(); }" },
  { category: "code", difficulty: "easy", content: "const numbers = [1, 2, 3, 4, 5]; const total = numbers.reduce((a, b) => a + b, 0);" },
  { category: "code", difficulty: "easy", content: "for (let i = 0; i < 10; i++) { console.log('Line number ' + i); }" },
  { category: "code", difficulty: "easy", content: "const user = { name: 'Ana', age: 30 }; console.log(user.name, user.age);" },
  { category: "code", difficulty: "easy", content: "function isEven(n) { return n % 2 === 0; } console.log(isEven(4));" },
  { category: "code", difficulty: "easy", content: "const items = ['a', 'b', 'c']; console.log(items.length); items.push('d');" },

  { category: "code", difficulty: "medium", content: "const [user, setUser] = useState({ name: '', email: '' }); const handleChange = (e) => { const { name, value } = e.target; setUser(prev => ({ ...prev, [name]: value })); };" },
  { category: "code", difficulty: "medium", content: "export async function getStaticProps() { const res = await fetch('https://api.example.com/posts'); const posts = await res.json(); return { props: { posts } }; }" },
  { category: "code", difficulty: "medium", content: "const filteredData = data.filter(item => item.isActive).map(item => item.value); console.log('Processed:', filteredData);" },
  { category: "code", difficulty: "medium", content: "app.get('/api/users/:id', async (req, res) => { const user = await User.findById(req.params.id); res.json(user); });" },
  { category: "code", difficulty: "medium", content: "const ThemeContext = createContext('dark'); export const ThemeProvider = ({ children }) => { return <ThemeContext.Provider value='light'>{children}</ThemeContext.Provider>; };" },
  { category: "code", difficulty: "medium", content: "const groupedByCategory = items.reduce((acc, item) => { (acc[item.category] = acc[item.category] || []).push(item); return acc; }, {});" },
  { category: "code", difficulty: "medium", content: "useEffect(() => { const timer = setInterval(() => setCount(c => c + 1), 1000); return () => clearInterval(timer); }, []);" },
  { category: "code", difficulty: "medium", content: "try { const data = JSON.parse(rawInput); process(data); } catch (err) { console.error('Invalid JSON:', err.message); }" },
  { category: "code", difficulty: "medium", content: "router.post('/login', async (req, res) => { const { email, password } = req.body; const token = await auth.signIn(email, password); res.json({ token }); });" },
  { category: "code", difficulty: "medium", content: "const sorted = [...products].sort((a, b) => b.price - a.price).slice(0, 5).map(p => p.name);" },

  { category: "code", difficulty: "hard", content: "type GenericResponse<T> = { data: T; status: number; message: string; }; async function fetchData<T>(url: string): Promise<GenericResponse<T>> { const response = await fetch(url); return response.json(); }" },
  { category: "code", difficulty: "hard", content: "const useDebounce = <T>(value: T, delay: number): T => { const [debouncedValue, setDebouncedValue] = useState<T>(value); useEffect(() => { const handler = setTimeout(() => setDebouncedValue(value), delay); return () => clearTimeout(handler); }, [value, delay]); return debouncedValue; };" },
  { category: "code", difficulty: "hard", content: "export const prisma = globalThis.prisma ?? new PrismaClient({ log: ['query', 'error', 'warn'] }); if (process.env.NODE_ENV !== 'production') globalThis.prisma = prisma;" },
  { category: "code", difficulty: "hard", content: "interface UserProps extends BaseProps { id: string; role: 'admin' | 'user'; }; const UserComponent: React.FC<UserProps> = ({ id, role, ...rest }) => { return <div {...rest}>{id} - {role}</div>; };" },
  { category: "code", difficulty: "hard", content: "const result = await prisma.$transaction(async (tx) => { const sender = await tx.account.update({ where: { id: 1 }, data: { balance: { decrement: 100 } } }); return sender; });" },
  { category: "code", difficulty: "hard", content: "type DeepPartial<T> = { [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P]; }; const merge = <T>(base: T, patch: DeepPartial<T>): T => ({ ...base, ...patch });" },
  { category: "code", difficulty: "hard", content: "const memoized = useMemo(() => data?.filter(x => x.active).reduce((s, x) => s + (x.value ?? 0), 0) ?? 0, [data]);" },
  { category: "code", difficulty: "hard", content: "export function createStore<S, A>(reducer: (state: S, action: A) => S, initial: S) { let state = initial; const listeners = new Set<() => void>(); return { dispatch: (a: A) => { state = reducer(state, a); listeners.forEach(l => l()); } }; }" },
  { category: "code", difficulty: "hard", content: "const pipe = <T>(...fns: Array<(arg: T) => T>) => (x: T): T => fns.reduce((acc, fn) => fn(acc), x); const clean = pipe<string>(s => s.trim(), s => s.toLowerCase());" },
  { category: "code", difficulty: "hard", content: "await Promise.all(urls.map(async (url) => { const res = await fetch(url, { headers: { Authorization: `Bearer ${token}` } }); if (!res.ok) throw new Error(`HTTP ${res.status}`); return res.json(); }));" },

  { category: "quotes", difficulty: "easy", content: "Be the change that you wish to see in the world. Happiness depends upon ourselves. It does not matter how slowly you go as long as you do not stop." },
  { category: "quotes", difficulty: "easy", content: "Believe you can and you are halfway there. Everything you have ever wanted is on the other side of fear. Success is walking from failure to failure with no loss of enthusiasm." },
  { category: "quotes", difficulty: "easy", content: "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you will know when you find it." },
  { category: "quotes", difficulty: "easy", content: "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma which is living with the results of other people's thinking. Stay hungry, stay foolish." },
  { category: "quotes", difficulty: "easy", content: "The future belongs to those who believe in the beauty of their dreams. Spread love everywhere you go. Let no one ever come to you without leaving happier than they arrived." },
  { category: "quotes", difficulty: "easy", content: "Life is what happens when you are busy making other plans. In three words I can sum up everything I have learned about life: it goes on. The best way to predict the future is to create it." },
  { category: "quotes", difficulty: "easy", content: "Whatever you are, be a good one. Keep your face always toward the sunshine and shadows will fall behind you. What you do today can improve all your tomorrows." },
  { category: "quotes", difficulty: "easy", content: "Happiness is not something ready made. It comes from your own actions. The only limit to our realization of tomorrow is our doubts of today. Dream big and dare to fail." },
  { category: "quotes", difficulty: "easy", content: "Start where you are. Use what you have. Do what you can. It always seems impossible until it is done. A journey of a thousand miles begins with a single step." },
  { category: "quotes", difficulty: "easy", content: "You miss one hundred percent of the shots you never take. If you can dream it, you can do it. Act as if what you do makes a difference. It does." },

  { category: "quotes", difficulty: "medium", content: "Nothing in the world is more dangerous than sincere ignorance and conscientious stupidity. The measure of a man is what he does with power. Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that." },
  { category: "quotes", difficulty: "medium", content: "In the end, it's not the years in your life that count. It's the life in your years. Our lives begin to end the day we become silent about things that matter. Injustice anywhere is a threat to justice everywhere." },
  { category: "quotes", difficulty: "medium", content: "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven. What we achieve inwardly will change outer reality. The only true wisdom is in knowing you know nothing." },
  { category: "quotes", difficulty: "medium", content: "It is during our darkest moments that we must focus to see the light. You will face many defeats in life, but never let yourself be defeated. The purpose of our lives is to be happy and to help others." },
  { category: "quotes", difficulty: "medium", content: "A person who never made a mistake never tried anything new. Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world and encourages progress." },
  { category: "quotes", difficulty: "medium", content: "Do not go where the path may lead, go instead where there is no path and leave a trail. To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment." },
  { category: "quotes", difficulty: "medium", content: "Success is not final, failure is not fatal: it is the courage to continue that counts. A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty. Never let a good crisis go to waste." },
  { category: "quotes", difficulty: "medium", content: "We cannot solve our problems with the same thinking we used when we created them. The important thing is not to stop questioning. Curiosity has its own reason for existing. Learn from yesterday, live for today, hope for tomorrow." },
  { category: "quotes", difficulty: "medium", content: "The greatest glory in living lies not in never falling, but in rising every time we fall. Education is the most powerful weapon which you can use to change the world. It always seems impossible until someone finally does it." },
  { category: "quotes", difficulty: "medium", content: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light. It does not do to dwell on dreams and forget to live. Words are our most inexhaustible source of magic." },
  { category: "quotes", difficulty: "medium", content: "Twenty years from now you will be more disappointed by the things that you did not do than by the ones you did do. So throw off the bowlines, sail away from the safe harbor, and catch the trade winds in your sails." },

  { category: "quotes", difficulty: "hard", content: "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion. He who has a why to live can bear almost any how. Freedom is what you do with what's been done to you." },
  { category: "quotes", difficulty: "hard", content: "The unexamined life is not worth living for a human being. We are what we repeatedly do. Excellence, then, is not an act, but a habit. Character is destiny. To find yourself, think for yourself and challenge every dogma." },
  { category: "quotes", difficulty: "hard", content: "Man is condemned to be free; because once thrown into the world, he is responsible for everything he does. It is not that we have a short time to live, but that we waste much of it. Life is long if you know how to use it." },
  { category: "quotes", difficulty: "hard", content: "Out of the night that covers me, black as the pit from pole to pole, I thank whatever gods may be for my unconquerable soul. I am the master of my fate, I am the captain of my soul. My head is bloody, but unbowed." },
  { category: "quotes", difficulty: "hard", content: "He who fights with monsters should look to it that he himself does not become a monster. And if you gaze long into an abyss, the abyss also gazes into you. That which does not kill us makes us stronger, and what is done out of love always takes place beyond good and evil." },
  { category: "quotes", difficulty: "hard", content: "I have learned to seek my happiness by limiting my desires, rather than in attempting to satisfy them. The mind, in proportion as it comprehends more things by the second kind of knowledge, is less subjected to those affects which are evil, and stands in less fear of death." },
  { category: "quotes", difficulty: "hard", content: "We are not permitted to choose the frame of our destiny. But what we put into it is ours. Whatever the struggle, continue the climb. It may be only one step to the summit. The privilege of a lifetime is to become who you truly are, beyond convention and beyond fear." },
  { category: "quotes", difficulty: "hard", content: "Between stimulus and response there is a space. In that space is our power to choose our response. In our response lies our growth and our freedom. Everything can be taken from a man but one thing: the last of the human freedoms, to choose one's attitude in any given set of circumstances." },
  { category: "quotes", difficulty: "hard", content: "Beauty is no quality in things themselves: it exists merely in the mind which contemplates them, and each mind perceives a different beauty. Custom, then, is the great guide of human life. It is that principle alone which renders our experience useful to us." },

  { category: "lyrics", difficulty: "easy", content: "Wise men say only fools rush in. But I can't help falling in love with you. Shall I stay? Would it be a sin if I can't help falling in love with you? Like a river flows surely to the sea, darling so it goes, some things are meant to be." },
  { category: "lyrics", difficulty: "easy", content: "I see trees of green, red roses too. I see them bloom for me and you. And I think to myself what a wonderful world. I see skies of blue and clouds of white. The bright blessed day, the dark sacred night. And I think to myself what a wonderful world." },
  { category: "lyrics", difficulty: "easy", content: "All you need is love, love. Love is all you need. There's nothing you can do that can't be done. Nothing you can sing that can't be sung. Nothing you can say, but you can learn how to play the game. It's easy. All you need is love." },
  { category: "lyrics", difficulty: "easy", content: "Every breath you take and every move you make. Every bond you break, every step you take, I'll be watching you. Every single day and every word you say. Every game you play, every night you stay, I'll be watching you. Oh can't you see you belong to me?" },
  { category: "lyrics", difficulty: "easy", content: "Imagine there's no heaven, it's easy if you try. No hell below us, above us only sky. Imagine all the people living for today. Imagine there's no countries, it isn't hard to do. Nothing to kill or die for, and no religion too. Imagine all the people living life in peace." },
  { category: "lyrics", difficulty: "easy", content: "Hey Jude, don't make it bad. Take a sad song and make it better. Remember to let her into your heart, then you can start to make it better. Hey Jude, don't be afraid. You were made to go out and get her. The minute you let her under your skin, then you begin to make it better." },
  { category: "lyrics", difficulty: "easy", content: "Here comes the sun, here comes the sun, and I say it's all right. Little darling, it's been a long cold lonely winter. Little darling, it feels like years since it's been here. Here comes the sun, here comes the sun, and I say it's all right." },
  { category: "lyrics", difficulty: "easy", content: "Country roads, take me home to the place I belong. West Virginia, mountain momma, take me home, country roads. All my memories gather round her, miner's lady, stranger to blue water. Dark and dusty, painted on the sky, misty taste of moonshine, teardrop in my eye." },
  { category: "lyrics", difficulty: "easy", content: "Don't stop believin', hold on to that feelin'. Streetlight people, don't stop believin'. Hold on to that feelin'. Streetlight people, don't stop believin'. Hold on to that feelin'. Streetlight people, don't stop believin'. Hold on to that feelin'." },
  { category: "lyrics", difficulty: "easy", content: "Twinkle, twinkle, little star, how I wonder what you are. Up above the world so high, like a diamond in the sky. Twinkle, twinkle, little star, how I wonder what you are. When the blazing sun is gone, when he nothing shines upon, then you show your little light, twinkle, twinkle, all the night." },

  { category: "lyrics", difficulty: "medium", content: "Is this the real life? Is this just fantasy? Caught in a landslide, no escape from reality. Open your eyes, look up to the skies and see. I'm just a poor boy, I need no sympathy. Because I'm easy come, easy go, little high, little low. Anyway the wind blows doesn't really matter to me." },
  { category: "lyrics", difficulty: "medium", content: "Hello darkness, my old friend. I've come to talk with you again. Because a vision softly creeping, left its seeds while I was sleeping. And the vision that was planted in my brain still remains within the sound of silence. In restless dreams I walked alone narrow streets of cobblestone." },
  { category: "lyrics", difficulty: "medium", content: "Just a small town girl, livin' in a lonely world. She took the midnight train goin' anywhere. Just a city boy, born and raised in South Detroit. He took the midnight train goin' anywhere. A singer in a smoky room, a smell of wine and cheap perfume. For a smile they can share the night." },
  { category: "lyrics", difficulty: "medium", content: "Pressure pushing down on me, pressing down on you, no man ask for. Under pressure that burns a building down, splits a family in two, puts people on streets. It's the terror of knowing what this world is about. Watching some good friends screaming let me out! Pray tomorrow gets me higher." },
  { category: "lyrics", difficulty: "medium", content: "Mama, take this badge off of me. I can't use it anymore. It's getting dark, too dark to see. I feel I'm knockin' on heaven's door. Knock, knock, knockin' on heaven's door. That long black cloud is comin' down. I feel I'm knockin' on heaven's door." },
  { category: "lyrics", difficulty: "medium", content: "I can't get no satisfaction, I can't get no satisfaction. 'Cause I try and I try and I try and I try. I can't get no, I can't get no. When I'm drivin' in my car, and a man comes on the radio. He's tellin' me more and more about some useless information. Supposed to fire my imagination." },
  { category: "lyrics", difficulty: "medium", content: "Should I stay or should I go now? If I go there will be trouble. And if I stay it will be double. So come on and let me know. Should I stay or should I go now? If I go there will be trouble. And if I stay it will be double. So come on and let me know." },
  { category: "lyrics", difficulty: "medium", content: "We will, we will rock you. We will, we will rock you. Buddy you're a boy make a big noise. Playin' in the street gonna be a big man someday. You got mud on your face, you big disgrace. Kickin' your can all over the place, singin'. We will, we will rock you." },
  { category: "lyrics", difficulty: "medium", content: "Hotel California, such a lovely place, such a lovely face. Plenty of room at the Hotel California. Any time of year, you can find it here. Her mind is Tiffany-twisted, she got the Mercedes bends. She got a lot of pretty, pretty boys that she calls friends. How they dance in the courtyard, sweet summer sweat." },
  { category: "lyrics", difficulty: "medium", content: "Another one bites the dust. Another one bites the dust. And another one gone, and another one gone. Another one bites the dust. Hey, I'm gonna get you too. Another one bites the dust. How do you think I'm going to get along without you when you're gone? You took me for everything that I had and kicked me out on my own." },
  { category: "lyrics", difficulty: "medium", content: "She's a killer queen, gunpowder, gelatine. Dynamite with a laser beam. Guaranteed to blow your mind. Anytime. Recommended at the price. Insatiable an appetite. Wanna try? To avoid complications. She never kept the same address. In conversation, she spoke just like a baroness." },

  { category: "lyrics", difficulty: "hard", content: "The words of the prophets are written on the subway walls and tenement halls, and whispered in the sounds of silence. And the people bowed and prayed to the neon god they made. And the sign flashed out its warning in the words that it was forming. And the sign said, the words of the prophets are written on the subway walls." },
  { category: "lyrics", difficulty: "hard", content: "Look, if you had one shot or one opportunity to seize everything you ever wanted in one moment. Would you capture it or just let it slip? Yo, his palms are sweaty, knees weak, arms are heavy. There's vomit on his sweater already, mom's spaghetti. He's nervous, but on the surface he looks calm and ready to drop bombs." },
  { category: "lyrics", difficulty: "hard", content: "And as I hung up the phone it occurred to me, he'd grown up just like me. My boy was just like me. And the cat's in the cradle and the silver spoon, little boy blue and the man in the moon. When you coming home, dad? I don't know when, but we'll get together then. You know we'll have a good time then." },
  { category: "lyrics", difficulty: "hard", content: "In the desert you can remember your name, for there ain't no one for to give you no pain. La, la, la, la, la, la. After nine days I let the horse run free, 'cause the desert had turned to sea. There were plants and birds and rocks and things. There was sand and hills and rings. The ocean is a desert with its life underground." },
  { category: "lyrics", difficulty: "hard", content: "The dawn is breaking. A light shining through. You're barely waking. And I'm tangled up in you. I'm open, you're closed. Where I'll follow, you'll go. I worry I won't see your face light up again. Even the best fall down sometimes. Even the wrong words seem to rhyme. Out of the doubt that fills my mind." },
  { category: "lyrics", difficulty: "hard", content: "Breathe, breathe in the air. Don't be afraid to care. Leave but don't leave me. Look around and choose your own ground. For long you live and high you fly. And smiles you'll give and tears you'll cry. And all you touch and all you see. Is all your life will ever be." },
  { category: "lyrics", difficulty: "hard", content: "There must be some kind of way out of here, said the joker to the thief. There's too much confusion, I can't get no relief. Businessmen, they drink my wine, plowmen dig my earth. None of them along the line know what any of it is worth. No reason to get excited, the thief he kindly spoke. There are many here among us who feel that life is but a joke." },
  { category: "lyrics", difficulty: "hard", content: "I have become comfortably numb. I have become comfortably numb. There is no pain, you are receding. A distant ship's smoke on the horizon. You are only coming through in waves. Your lips move but I can't hear what you're saying. When I was a child I had a fever. My hands felt just like two balloons." },
  { category: "lyrics", difficulty: "hard", content: "Round and round the family, possessions are forever. Part of the machine, just a cog in the wheel. You can have it all, you can have it all. But you can't touch the sky. You can have it all, but you can't touch the sky. You can have it all, you can have it all. But you can't touch the sky." },
  { category: "lyrics", difficulty: "hard", content: "I've looked at life from both sides now, from win and lose and still somehow. It's life's illusions I recall. I really don't know life at all. I've looked at clouds from both sides now, from up and down and still somehow. It's cloud illusions I recall. I really don't know clouds at all." },
  { category: "lyrics", difficulty: "hard", content: "Close your eyes, have no fear, the monster's gone, he's on the run and your daddy's here. Beautiful, beautiful, beautiful boy. Before you go to sleep, say a little prayer. Every day in every way, it's getting better and better. Beautiful, beautiful, beautiful boy." },

  { category: "general", difficulty: "easy", language: "pt", content: "O sol se punha atrás das montanhas, tingindo o céu de laranja e rosa sobre o vale tranquilo. Uma brisa suave passava entre as folhas das árvores antigas, e o ar cheirava a terra molhada e a flores do campo. Era o fim de tarde perfeito para uma longa caminhada, longe do barulho e da pressa da cidade grande." },
  { category: "general", difficulty: "easy", language: "pt", content: "Aprender a cozinhar pode ser uma experiência muito gratificante para quem gosta de boa comida e de passar tempo na cozinha. Começar com receitas simples, como massas e saladas, ajuda a ganhar confiança antes de tentar pratos mais elaborados. Dividir uma refeição feita em casa com os amigos e a família é uma das melhores formas de passar a tarde." },
  { category: "general", difficulty: "easy", language: "pt", content: "Muita gente descobre que manter um diário ajuda a organizar os pensamentos e a reduzir o estresse depois de um dia cheio. Escrever seus objetivos e reflexões permite acompanhar o próprio progresso e perceber o quanto você cresceu ao longo do tempo. Bastam alguns minutos pela manhã para começar o dia com uma disposição mais leve e positiva." },
  { category: "general", difficulty: "medium", language: "pt", content: "A transição global para fontes de energia renovável ganha força à medida que os países tentam cumprir suas metas climáticas. A energia solar e a eólica estão cada vez mais baratas e já superam os combustíveis fósseis em vários mercados. Ainda assim, a mudança exige investimento pesado em infraestrutura e em armazenamento para garantir uma rede elétrica estável e confiável." },
  { category: "general", difficulty: "medium", language: "pt", content: "A inteligência emocional é cada vez mais reconhecida como uma peça essencial da liderança no ambiente corporativo moderno. Líderes com autoconsciência e empatia lidam melhor com relações complexas e criam uma cultura de colaboração entre as equipes. Ao valorizar o bem-estar e o crescimento das pessoas, eles impulsionam o sucesso e a inovação de suas organizações a longo prazo." },
  { category: "general", difficulty: "medium", language: "pt", content: "O trabalho remoto transformou por completo a relação entre os funcionários e o escritório tradicional. Se por um lado oferece mais flexibilidade e autonomia, por outro traz novos desafios de comunicação e de equilíbrio entre a vida pessoal e a profissional. Muitas empresas agora repensam suas políticas para atrair talentos sem perder a coesão da cultura interna." },
  { category: "general", difficulty: "hard", language: "pt", content: "Os fundamentos epistemológicos da ciência contemporânea exigem uma adesão rigorosa aos princípios da falsificação empírica. Modelos teóricos precisam ser submetidos a um escrutínio exaustivo e à revisão por pares para que sua validade seja aceita pela comunidade acadêmica. Essa busca incansável pela verdade objetiva permanece como a pedra angular do progresso intelectual humano, para além de fronteiras ideológicas." },
  { category: "general", difficulty: "hard", language: "pt", content: "As ramificações socioeconômicas da globalização produziram, ao mesmo tempo, prosperidade sem precedentes e desigualdades estruturais em diversas regiões do planeta. Embora o comércio internacional tenha facilitado a troca de bens e ideias, também aprofundou a distância entre nações desenvolvidas e em desenvolvimento. Enfrentar essas disparidades requer reforma política, desenvolvimento sustentável e distribuição mais justa de recursos." },
  { category: "general", difficulty: "hard", language: "pt", content: "A neuroplasticidade, a notável capacidade do cérebro de reorganizar suas conexões em resposta à experiência, revolucionou nossa compreensão da cognição e da reabilitação. Esse fenômeno adaptativo sustenta o aprendizado, a consolidação da memória e a recuperação após lesões neurológicas ao longo de toda a vida. Por isso, intervenções terapêuticas cada vez mais recorrem à estimulação direcionada para ativar os mecanismos de reparo do próprio cérebro." },

  { category: "general", difficulty: "easy", language: "es", content: "El sol se ocultaba tras las montañas, tiñendo el cielo de naranja y rosa sobre el valle tranquilo. Una brisa suave pasaba entre las hojas de los árboles antiguos y el aire olía a tierra mojada y a flores del campo. Era la tarde perfecta para dar un largo paseo, lejos del ruido y las prisas de la gran ciudad." },
  { category: "general", difficulty: "easy", language: "es", content: "Aprender a cocinar puede ser una experiencia muy gratificante para quien disfruta de la buena comida y de pasar tiempo en la cocina. Empezar con recetas sencillas, como pastas o ensaladas, ayuda a ganar confianza antes de intentar platos más complejos. Compartir una comida casera con amigos y familia es una de las mejores maneras de pasar la tarde." },
  { category: "general", difficulty: "easy", language: "es", content: "Muchas personas descubren que llevar un diario les ayuda a ordenar sus pensamientos y a reducir el estrés después de un día largo. Escribir tus metas y reflexiones te permite seguir tu propio progreso y notar cuánto has crecido con el tiempo. Bastan unos minutos por la mañana para empezar el día con una actitud más ligera y positiva." },
  { category: "general", difficulty: "medium", language: "es", content: "La transición global hacia las energías renovables cobra impulso a medida que los países intentan cumplir sus objetivos climáticos. La energía solar y la eólica son cada vez más económicas y ya superan a los combustibles fósiles en muchos mercados. Sin embargo, el cambio exige una fuerte inversión en infraestructura y almacenamiento para garantizar una red eléctrica estable y fiable." },
  { category: "general", difficulty: "medium", language: "es", content: "La inteligencia emocional se reconoce cada vez más como un componente esencial del liderazgo en el entorno empresarial moderno. Los líderes con autoconciencia y empatía manejan mejor las relaciones complejas y fomentan una cultura de colaboración entre los equipos. Al priorizar el bienestar y el crecimiento de las personas, impulsan el éxito y la innovación de sus organizaciones a largo plazo." },
  { category: "general", difficulty: "medium", language: "es", content: "El trabajo remoto ha transformado por completo la relación entre los empleados y la oficina tradicional. Aunque ofrece mayor flexibilidad y autonomía, también plantea nuevos retos de comunicación y de equilibrio entre la vida personal y la profesional. Muchas empresas replantean ahora sus políticas para atraer talento sin perder la cohesión de su cultura interna." },
  { category: "general", difficulty: "hard", language: "es", content: "Los fundamentos epistemológicos de la ciencia contemporánea exigen una adhesión rigurosa a los principios de la falsación empírica. Los marcos teóricos deben someterse a un escrutinio exhaustivo y a la revisión por pares para que su validez sea aceptada por la comunidad académica. Esta búsqueda incansable de la verdad objetiva sigue siendo la piedra angular del progreso intelectual humano." },
  { category: "general", difficulty: "hard", language: "es", content: "Las ramificaciones socioeconómicas de la globalización han generado a la vez una prosperidad sin precedentes y desigualdades estructurales en distintas regiones del mundo. Aunque el comercio internacional ha facilitado el intercambio de bienes e ideas, también ha ampliado la brecha entre las naciones desarrolladas y las que están en desarrollo. Abordar estas disparidades requiere reformas políticas y una distribución más justa de los recursos." },
  { category: "general", difficulty: "hard", language: "es", content: "La neuroplasticidad, la notable capacidad del cerebro para reorganizar sus conexiones en respuesta a la experiencia, ha revolucionado nuestra comprensión de la cognición y la rehabilitación. Este fenómeno adaptativo sustenta el aprendizaje, la consolidación de la memoria y la recuperación tras una lesión neurológica a lo largo de toda la vida. Por ello, las terapias recurren cada vez más a la estimulación dirigida para activar los mecanismos de reparación del propio cerebro." },

  { category: "general", difficulty: "easy", language: "fr", content: "Le soleil se couchait derrière les montagnes, teintant le ciel d'orange et de rose au-dessus de la vallée tranquille. Une brise légère passait entre les feuilles des vieux arbres, et l'air sentait la terre humide et les fleurs des champs. C'était la fin d'après-midi idéale pour une longue promenade, loin du bruit et de l'agitation de la grande ville." },
  { category: "general", difficulty: "easy", language: "fr", content: "Apprendre à cuisiner peut être une expérience très gratifiante pour ceux qui aiment la bonne nourriture et passer du temps en cuisine. Commencer par des recettes simples, comme des pâtes ou des salades, aide à gagner en confiance avant d'essayer des plats plus élaborés. Partager un repas fait maison avec ses amis et sa famille est l'une des plus belles façons de passer l'après-midi." },
  { category: "general", difficulty: "easy", language: "fr", content: "Beaucoup de gens constatent que tenir un journal les aide à organiser leurs pensées et à réduire le stress après une longue journée. Écrire ses objectifs et ses réflexions permet de suivre ses progrès et de mesurer le chemin parcouru au fil du temps. Quelques minutes le matin suffisent pour commencer la journée avec un état d'esprit plus léger et positif." },
  { category: "general", difficulty: "medium", language: "fr", content: "La transition mondiale vers les énergies renouvelables prend de l'ampleur à mesure que les pays cherchent à atteindre leurs objectifs climatiques. L'énergie solaire et l'énergie éolienne deviennent de plus en plus abordables et dépassent déjà les combustibles fossiles sur de nombreux marchés. Toutefois, cette transition exige d'importants investissements dans les infrastructures et le stockage pour garantir un réseau électrique stable et fiable." },
  { category: "general", difficulty: "medium", language: "fr", content: "L'intelligence émotionnelle est de plus en plus reconnue comme un élément essentiel du leadership dans le monde de l'entreprise moderne. Les dirigeants dotés de conscience de soi et d'empathie gèrent mieux les relations complexes et favorisent une culture de collaboration au sein des équipes. En donnant la priorité au bien-être et à la croissance des personnes, ils stimulent la réussite et l'innovation de leurs organisations." },
  { category: "general", difficulty: "medium", language: "fr", content: "Le télétravail a profondément transformé la relation entre les salariés et le bureau traditionnel. S'il offre plus de flexibilité et d'autonomie, il pose aussi de nouveaux défis en matière de communication et d'équilibre entre la vie personnelle et la vie professionnelle. De nombreuses entreprises repensent aujourd'hui leurs politiques pour attirer les talents sans perdre la cohésion de leur culture interne." },
  { category: "general", difficulty: "hard", language: "fr", content: "Les fondements épistémologiques de la science contemporaine exigent une adhésion rigoureuse aux principes de la falsifiabilité empirique. Les cadres théoriques doivent être soumis à un examen approfondi et à l'évaluation par les pairs afin que leur validité soit reconnue par la communauté scientifique. Cette quête incessante de la vérité objective demeure la pierre angulaire du progrès intellectuel humain." },
  { category: "general", difficulty: "hard", language: "fr", content: "Les ramifications socio-économiques de la mondialisation ont engendré à la fois une prospérité sans précédent et des inégalités structurelles dans diverses régions du monde. Si le commerce international a facilité l'échange de biens et d'idées, il a aussi creusé l'écart entre les pays développés et les pays en développement. Réduire ces disparités suppose des réformes politiques et une répartition plus équitable des ressources." },
  { category: "general", difficulty: "hard", language: "fr", content: "La neuroplasticité, cette capacité remarquable du cerveau à réorganiser ses connexions en réponse à l'expérience, a bouleversé notre compréhension de la cognition et de la rééducation. Ce phénomène adaptatif sous-tend l'apprentissage, la consolidation de la mémoire et la récupération après une lésion neurologique tout au long de la vie. C'est pourquoi les thérapies recourent de plus en plus à une stimulation ciblée pour activer les mécanismes de réparation du cerveau." },

  { category: "general", difficulty: "easy", language: "de", content: "Die Sonne ging hinter den Bergen unter und färbte den Himmel über dem stillen Tal orange und rosa. Eine sanfte Brise strich durch die Blätter der alten Bäume, und die Luft roch nach feuchter Erde und Wiesenblumen. Es war der perfekte Nachmittag für einen langen Spaziergang, weit weg vom Lärm und der Hektik der großen Stadt." },
  { category: "general", difficulty: "easy", language: "de", content: "Kochen zu lernen kann eine sehr lohnende Erfahrung sein für alle, die gutes Essen mögen und gern Zeit in der Küche verbringen. Mit einfachen Rezepten wie Nudeln oder Salaten zu beginnen hilft, Sicherheit zu gewinnen, bevor man sich an schwierigere Gerichte wagt. Eine selbst gekochte Mahlzeit mit Freunden und Familie zu teilen ist eine der schönsten Arten, den Nachmittag zu verbringen." },
  { category: "general", difficulty: "easy", language: "de", content: "Viele Menschen stellen fest, dass ein Tagebuch ihnen hilft, ihre Gedanken zu ordnen und nach einem langen Tag den Stress abzubauen. Wer seine Ziele und Gedanken aufschreibt, kann den eigenen Fortschritt verfolgen und erkennen, wie sehr er mit der Zeit gewachsen ist. Schon wenige Minuten am Morgen genügen, um den Tag mit einer leichteren und positiveren Haltung zu beginnen." },
  { category: "general", difficulty: "medium", language: "de", content: "Der weltweite Wandel hin zu erneuerbaren Energien gewinnt an Fahrt, während die Länder versuchen, ihre Klimaziele zu erreichen. Solar- und Windkraft werden immer günstiger und übertreffen fossile Brennstoffe bereits in vielen Märkten. Dennoch erfordert der Wandel erhebliche Investitionen in Infrastruktur und Speicher, um ein stabiles und zuverlässiges Stromnetz zu gewährleisten." },
  { category: "general", difficulty: "medium", language: "de", content: "Emotionale Intelligenz gilt zunehmend als wesentlicher Bestandteil guter Führung im modernen Arbeitsumfeld. Führungskräfte mit Selbstwahrnehmung und Empathie kommen besser mit komplexen Beziehungen zurecht und fördern eine Kultur der Zusammenarbeit im Team. Indem sie das Wohl und die Entwicklung der Menschen in den Vordergrund stellen, treiben sie den langfristigen Erfolg ihrer Organisationen voran." },
  { category: "general", difficulty: "medium", language: "de", content: "Die Arbeit aus der Ferne hat das Verhältnis zwischen Beschäftigten und dem klassischen Büro grundlegend verändert. Sie bietet zwar mehr Flexibilität und Eigenständigkeit, bringt aber auch neue Herausforderungen bei der Kommunikation und der Balance zwischen Beruf und Privatleben mit sich. Viele Unternehmen überdenken nun ihre Regeln, um Talente zu gewinnen, ohne den Zusammenhalt ihrer Kultur zu verlieren." },
  { category: "general", difficulty: "hard", language: "de", content: "Die erkenntnistheoretischen Grundlagen der modernen Wissenschaft verlangen ein striktes Festhalten an den Prinzipien der empirischen Falsifikation. Theoretische Modelle müssen einer gründlichen Prüfung und der Begutachtung durch Fachkollegen unterzogen werden, damit ihre Gültigkeit von der wissenschaftlichen Gemeinschaft anerkannt wird. Dieses unermüdliche Streben nach objektiver Wahrheit bleibt der Grundpfeiler des menschlichen Fortschritts." },
  { category: "general", difficulty: "hard", language: "de", content: "Die sozioökonomischen Folgen der Globalisierung haben zugleich beispiellosen Wohlstand und strukturelle Ungleichheiten in verschiedenen Regionen der Welt hervorgebracht. Der internationale Handel hat zwar den Austausch von Gütern und Ideen erleichtert, aber auch die Kluft zwischen entwickelten und sich entwickelnden Ländern vertieft. Diese Ungleichheiten anzugehen erfordert politische Reformen und eine gerechtere Verteilung der Ressourcen." },
  { category: "general", difficulty: "hard", language: "de", content: "Die Neuroplastizität, die bemerkenswerte Fähigkeit des Gehirns, seine Verbindungen als Reaktion auf Erfahrungen neu zu ordnen, hat unser Verständnis von Kognition und Rehabilitation verändert. Dieses anpassungsfähige Phänomen liegt dem Lernen, der Festigung des Gedächtnisses und der Erholung nach neurologischen Verletzungen ein Leben lang zugrunde. Deshalb setzen Therapien zunehmend auf gezielte Stimulation, um die Reparaturmechanismen des Gehirns zu aktivieren." },

  { category: "quotes", difficulty: "easy", language: "pt", content: "Água mole em pedra dura, tanto bate até que fura. Quem não arrisca não petisca. Devagar se vai ao longe, e com calma se chega mais perto do que se deseja alcançar." },
  { category: "quotes", difficulty: "easy", language: "pt", content: "Mais vale um pássaro na mão do que dois voando. Cada macaco no seu galho. Antes tarde do que nunca, mas melhor ainda é fazer as coisas no tempo certo, sem pressa e sem medo." },
  { category: "quotes", difficulty: "easy", language: "pt", content: "Quem semeia vento colhe tempestade. De grão em grão a galinha enche o papo. O barato sai caro quando a pressa fala mais alto do que o bom senso e a paciência." },
  { category: "quotes", difficulty: "medium", language: "pt", content: "Não se trata de esperar a tempestade passar, mas de aprender a dançar na chuva. A persistência realiza o impossível, e o que hoje parece um sonho distante amanhã pode ser apenas mais um passo já dado com coragem." },
  { category: "quotes", difficulty: "medium", language: "pt", content: "O sucesso não é definitivo e o fracasso não é fatal: o que importa é a coragem de continuar. Grandes jornadas começam com um único passo, e nenhum vento é favorável para quem não sabe aonde quer chegar." },
  { category: "quotes", difficulty: "medium", language: "pt", content: "A vida é dez por cento o que acontece com você e noventa por cento como você reage. Quem tem um porquê para viver suporta quase qualquer como, e transforma cada obstáculo em degrau para seguir adiante." },
  { category: "quotes", difficulty: "hard", language: "pt", content: "A verdadeira sabedoria está em reconhecer a extensão da própria ignorância. Conhecer os outros é inteligência; conhecer a si mesmo é a mais alta forma de discernimento. Dominar os outros exige força; dominar-se a si mesmo revela o verdadeiro poder." },
  { category: "quotes", difficulty: "hard", language: "pt", content: "Entre o estímulo e a resposta existe um espaço, e nesse espaço reside a nossa liberdade de escolher. É na escolha da nossa atitude diante das circunstâncias que se encontram o nosso crescimento e a nossa mais profunda dignidade humana." },
  { category: "quotes", difficulty: "hard", language: "pt", content: "A vida só pode ser compreendida olhando-se para trás, mas só pode ser vivida olhando-se para a frente. Não são os anos na vida que contam, mas a vida nos anos, e a intensidade com que ousamos habitar cada instante concedido." },

  { category: "quotes", difficulty: "easy", language: "es", content: "No dejes para mañana lo que puedas hacer hoy. A quien madruga, Dios le ayuda. Poco a poco se anda lejos, y con paciencia y calma se alcanza lo que de otro modo parecía imposible." },
  { category: "quotes", difficulty: "easy", language: "es", content: "Más vale pájaro en mano que ciento volando. El que no arriesga no gana. Nunca es tarde si la dicha es buena, y siempre hay tiempo para volver a empezar con más calma y confianza." },
  { category: "quotes", difficulty: "easy", language: "es", content: "Quien siembra vientos recoge tempestades. Ojos que no ven, corazón que no siente. De grano en grano se llena el granero, y con pequeños pasos se completan los caminos más largos." },
  { category: "quotes", difficulty: "medium", language: "es", content: "No se trata de esperar a que pase la tormenta, sino de aprender a bailar bajo la lluvia. La constancia logra lo que la fuerza no alcanza, y lo que hoy parece un sueño lejano mañana puede ser apenas un paso más ya dado." },
  { category: "quotes", difficulty: "medium", language: "es", content: "El éxito no es definitivo y el fracaso no es fatal: lo que cuenta es el valor para continuar. Grandes viajes empiezan con un solo paso, y ningún viento es favorable para quien no sabe a qué puerto se dirige." },
  { category: "quotes", difficulty: "medium", language: "es", content: "La vida es diez por ciento lo que te ocurre y noventa por ciento cómo reaccionas. Quien tiene un porqué para vivir puede soportar casi cualquier cómo, y convierte cada obstáculo en un peldaño hacia adelante." },
  { category: "quotes", difficulty: "hard", language: "es", content: "La verdadera sabiduría consiste en reconocer la magnitud de la propia ignorancia. Conocer a los demás es inteligencia; conocerse a uno mismo es la forma más alta de discernimiento. Dominar a otros exige fuerza; dominarse a uno mismo revela el verdadero poder." },
  { category: "quotes", difficulty: "hard", language: "es", content: "Entre el estímulo y la respuesta hay un espacio, y en ese espacio reside nuestra libertad para elegir. En la elección de nuestra actitud ante las circunstancias se encuentran nuestro crecimiento y nuestra dignidad más profunda." },
  { category: "quotes", difficulty: "hard", language: "es", content: "La vida solo puede comprenderse mirando hacia atrás, pero solo puede vivirse mirando hacia adelante. No son los años de la vida los que cuentan, sino la vida de los años y la intensidad con que nos atrevemos a habitar cada instante." },

  { category: "quotes", difficulty: "easy", language: "fr", content: "Petit à petit, l'oiseau fait son nid. Qui ne risque rien n'a rien. Rien ne sert de courir, il faut partir à point, et la patience vient à bout de tout ce que la hâte ne fait qu'abîmer." },
  { category: "quotes", difficulty: "easy", language: "fr", content: "Il ne faut pas remettre au lendemain ce que l'on peut faire le jour même. Un tiens vaut mieux que deux tu l'auras. Mieux vaut tard que jamais, mais mieux encore vaut agir au bon moment." },
  { category: "quotes", difficulty: "easy", language: "fr", content: "Qui sème le vent récolte la tempête. Petit à petit, on va loin. Chaque chose en son temps, et avec un peu de calme on arrive plus près de ce que l'on désire vraiment atteindre." },
  { category: "quotes", difficulty: "medium", language: "fr", content: "Il ne s'agit pas d'attendre que la tempête passe, mais d'apprendre à danser sous la pluie. La persévérance vient à bout de l'impossible, et ce qui semble aujourd'hui un rêve lointain peut n'être demain qu'un pas de plus déjà franchi." },
  { category: "quotes", difficulty: "medium", language: "fr", content: "Le succès n'est pas définitif et l'échec n'est pas fatal : c'est le courage de continuer qui compte. Les grands voyages commencent par un seul pas, et aucun vent n'est favorable à celui qui ne sait pas où il va." },
  { category: "quotes", difficulty: "medium", language: "fr", content: "La vie, c'est dix pour cent ce qui nous arrive et quatre-vingt-dix pour cent la façon dont nous réagissons. Celui qui a un pourquoi pour vivre peut supporter presque n'importe quel comment et transforme chaque obstacle en tremplin." },
  { category: "quotes", difficulty: "hard", language: "fr", content: "La véritable sagesse consiste à reconnaître l'étendue de sa propre ignorance. Connaître les autres est intelligence ; se connaître soi-même est la plus haute forme de discernement. Vaincre les autres demande de la force ; se vaincre soi-même révèle le vrai pouvoir." },
  { category: "quotes", difficulty: "hard", language: "fr", content: "Entre le stimulus et la réponse, il existe un espace, et dans cet espace réside notre liberté de choisir. C'est dans le choix de notre attitude face aux circonstances que se trouvent notre croissance et notre dignité la plus profonde." },
  { category: "quotes", difficulty: "hard", language: "fr", content: "La vie ne se comprend qu'en regardant en arrière, mais elle ne se vit qu'en regardant en avant. Ce ne sont pas les années de la vie qui comptent, mais la vie que l'on met dans les années et l'intensité avec laquelle on ose habiter chaque instant." },

  { category: "quotes", difficulty: "easy", language: "de", content: "Wer nicht wagt, der nicht gewinnt. Übung macht den Meister. Was du heute kannst besorgen, das verschiebe nicht auf morgen, denn mit ruhiger Beharrlichkeit kommt man am weitesten." },
  { category: "quotes", difficulty: "easy", language: "de", content: "Morgenstund hat Gold im Mund. Eile mit Weile. Der frühe Vogel fängt den Wurm, doch wer mit Geduld und Ruhe geht, kommt oft näher an das Ziel, als er es sich erhofft hatte." },
  { category: "quotes", difficulty: "easy", language: "de", content: "Wer Wind sät, wird Sturm ernten. Steter Tropfen höhlt den Stein. Von nichts kommt nichts, und mit kleinen Schritten legt man mit der Zeit auch die längsten Wege zurück." },
  { category: "quotes", difficulty: "medium", language: "de", content: "Es geht nicht darum, auf das Ende des Sturms zu warten, sondern zu lernen, im Regen zu tanzen. Beharrlichkeit vollbringt das scheinbar Unmögliche, und was heute wie ein ferner Traum wirkt, kann morgen nur ein weiterer bereits getaner Schritt sein." },
  { category: "quotes", difficulty: "medium", language: "de", content: "Erfolg ist nicht endgültig und Misserfolg nicht tödlich: Es ist der Mut weiterzumachen, der zählt. Große Reisen beginnen mit einem einzigen Schritt, und kein Wind ist günstig für den, der nicht weiß, wohin er will." },
  { category: "quotes", difficulty: "medium", language: "de", content: "Das Leben besteht zu zehn Prozent aus dem, was uns geschieht, und zu neunzig Prozent daraus, wie wir darauf reagieren. Wer ein Warum zum Leben hat, erträgt fast jedes Wie und macht aus jedem Hindernis eine Stufe nach oben." },
  { category: "quotes", difficulty: "hard", language: "de", content: "Wahre Weisheit besteht darin, das Ausmaß der eigenen Unwissenheit zu erkennen. Andere zu kennen ist Klugheit; sich selbst zu kennen ist die höchste Form der Einsicht. Andere zu beherrschen erfordert Stärke; sich selbst zu beherrschen offenbart wahre Macht." },
  { category: "quotes", difficulty: "hard", language: "de", content: "Zwischen Reiz und Reaktion liegt ein Raum, und in diesem Raum liegt unsere Freiheit zu wählen. In der Wahl unserer Haltung gegenüber den Umständen liegen unser Wachstum und unsere tiefste menschliche Würde begründet." },
  { category: "quotes", difficulty: "hard", language: "de", content: "Das Leben kann nur rückwärts verstanden, aber nur vorwärts gelebt werden. Es sind nicht die Jahre in unserem Leben, die zählen, sondern das Leben in unseren Jahren und die Intensität, mit der wir jeden Augenblick zu bewohnen wagen." },
];

async function main() {
  console.log('Starting PostgreSQL seed...');
  await prisma.text.deleteMany();

  for (const text of textData) {
    await prisma.text.create({
      data: {
        content: text.content,
        category: text.category,
        difficulty: text.difficulty,
        language: text.language ?? "en"
      },
    });
  }

  console.log(`✅ Seed completed! ${textData.length} texts inserted.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });